version: '3'

services:
        fuseki:
                environment:
                        - FUSEKI_VERSION=4.9.0

                image: mobr/fuseki
                expose:
                        - 3030
                ports:
                        - 3030:3030
                command: ["/jena-fuseki/fuseki-server", "--update", "--tdb2", "--verbose", "--debug"]
                container_name: fuseki

        flask:
                build: ./
                image: 'mobr/pap'
                tty: true
                ports:
                        - 5000:5000
                depends_on:
                        - fuseki
                command: [ "./wait-for-it.sh", "-t", "20", "fuseki:3030", "--", "python", "pap/app.py", "-fu",  "http://fuseki:3030"]
                container_name: pap
