swagger: "2.0"
info:
  description: "This is the api documentation for pap."
  version: "0.0.1"
  title: "PAP -- powered by mobr"
  termsOfService: "https://mobr.ai"
  contact:
    email: "apiteam@moondash.app"
  license:
    name: "Apache license"
host: "127.0.0.1:5000"
basePath: "/"
tags:
- name: "kbm"
  description: "Knowledge Base management"
- name: "cnl"
  description: "Available at the end of stage 3: CNL endpoints"
- name: "queries"
  description: "Available at the end of stage 4: Query engine endpoints"
- name: "visualization"
  description: "Available at the end of stage 5: Informative artifacts and dashboard endpoints"
schemes:
- "http"
paths:
  /kbm/getConcepts:
    get:
      tags:
      - "kbm"
      summary: "get all concepts"
      description: ""
      operationId: "kbm_concepts"
      responses:
        "200":
          description: "successful operation"
        "304":
          description: "Exception was raised"
        "400":
          description: "Invalid parameters supplied"

  /kbm/getProperties:
    get:
      tags:
      - "kbm"
      summary: "get all properties"
      description: ""
      operationId: "kbm_properties"
      responses:
        "200":
          description: "successful operation"
        "304":
          description: "Exception was raised"
        "400":
          description: "Invalid parameters supplied"

  /kbm/getParent/{entity_name}:
    get:
      tags:
      - "kbm"
      summary: "get the parent of a specific entity"
      description: ""
      operationId: "kbm_get_parent"
      parameters:
      - name: "entity_name"
        in: "path"
        description: "Entity name. E.g.: Parachain"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
        "304":
          description: "Exception was raised"
        "400":
          description: "Invalid parameters supplied"

  /kbm/getChildren/{entity_name}:
    get:
      tags:
      - "kbm"
      summary: "get the children of a specific entity"
      description: ""
      operationId: "kbm_get_children"
      parameters:
      - name: "entity_name"
        in: "path"
        description: "Entity name. E.g.: DistributedLedger"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
        "304":
          description: "Exception was raised"
        "400":
          description: "Invalid parameters supplied"

  /kbm/defineEntity/{entity_name}:
    get:
      tags:
      - "kbm"
      summary: "get the definition of a specific entity"
      description: ""
      operationId: "kbm_define_entity"
      parameters:
      - name: "entity_name"
        in: "path"
        description: "Entity name. E.g.: DistributedLedger"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
        "304":
          description: "Exception was raised"
        "400":
          description: "Invalid parameters supplied"

  /kbm/sparql_query:
    get:
      tags:
      - "kbm"
      summary: "query using sparql query language"
      description: ""
      operationId: "sparql_query"
      responses:
        "200":
          description: "successful operation"
        "304":
          description: "Exception was raised"
        "400":
          description: "Invalid parameters supplied"

  /kbm/knowledge_injection:
    get:
      tags:
      - "kbm"
      summary: "injection of knowledge specified in a turtle file"
      description: ""
      operationId: "inject_turtle"
      responses:
        "200":
          description: "successful operation"
        "304":
          description: "Exception was raised"
        "400":
          description: "Invalid parameters supplied"


externalDocs:
  description: "Find out more about PAP"
  url: "http://mobr.ai"